name: generate animation

on:
  # her 24 saatte bir otomatik çalışır
  schedule:
    - cron: "0 */24 * * *" 
  
  # elle tetiklemeye izin verir
  workflow_dispatch:
  
  # master (veya main) branch'e her push'ta çalışır
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # snake animasyonunu üret
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: yavuzbeydogan  # ← SENİN kullanıcı adın
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      # output branch'ine dosyaları gönder
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
